pipeline:
  identifier: Build_aboubacardiaby_dataservice_1710036111321
  name: Build dataservice
  orgIdentifier: default
  projectIdentifier: dataservice
  properties:
    ci:
      codebase:
        build: <+input>
        connectorRef: account.Github
        repoName: aboubacardiaby/dataservice
  stages:
    - stage:
        identifier: build
        name: build
        spec:
          cloneCodebase: true
          execution:
            steps:
              - step:
                  identifier: echo
                  name: echo
                  spec:
                    command: echo hello world
                  timeout: ""
                  type: Run
              - step:
                  identifier: dockerbuild
                  name: docker_build
                  spec:
                    connectorRef: docker_conn
                    image: plugins/docker
                    settings:
                      dry_run: "true"
                      password: <+input>
                      repo: hello/world
                      tags: latest
                      username: <+input>
                  timeout: ""
                  type: Plugin
          platform:
            os: Linux
            arch: Amd64
          runtime:
            type: Docker
            spec: {}
        type: CI
